# espanso configuration file 

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # Bear Bi-directional link
  - trigger: ":blink"
    replace: "---\n\n## Other References\nReferences to [{{clipboard}}](bear://x-callback-url/search?term=%22{{output}}%22)\n\n[{{mydate}}]" 
    vars:
      - name: clipboard
        type: clipboard
      - name: mydate
        type: date
        params:
          format: "%b %d, %Y at %I:%M %p"
      - name: output
        type: script
        params:
          args:
            - python
            - /Users/YOUR_USER_NAME_HERE/Library/Preferences/espanso/script_replace-spaces.py

  # Bear Bi-directional date
  - trigger: ":bidate"
    replace: "---\n\n## Other References\nReferences to [{{mydate}}](bear://x-callback-url/search?term=%22{{bb}}%20{{dd}}%2C%20{{yy}}%22)\n\n#.daily"
    vars:
      - name: mydate
        type: date
        params:
          format: "%b %d, %Y"
      - name: bb
        type: date
        params:
          format: "%b"
      - name: dd
        type: date
        params:
          format: "%d"
      - name: yy
        type: date
        params:
          format: "%Y"
