# espanso configuration file
# MAKE SURE TO HAVE THE PROPER PATH TO THE PYTHON SCRIPT.  Right click the python script and hold alt, you should see an option to copy the path, then replace the entire path "/Users/YOURUSERNAME/Library/Preferences/espanso/script_replace-spaces.py" 



# You can refer to the official documentation:
# https://espanso.org/docs/



matches:
# Bear Bi-directional link
  - trigger: ":blink"
    replace: "---\n\n## Other References\nReferences to [{{clipboard}}](bear://x-callback-url/search?term=%22{{output}}%22)\n\n[{{mydate}}]" 
    vars:
      - name: clipboard
        type: clipboard
      - name: mydate
        type: date
        params:
          format: "%b %d, %Y at %I:%M %p"
      - name: output
        type: script
        params:
          args:
            - python
            - /Users/USERNAME/Library/Preferences/espanso/script_replace-spaces.py
